import './global.css';
import { Providers } from './providers';

export const metadata = {
  title: 'Welcome to tailwind-theming-demo',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>{children}</Providers>
    </html>
  );
}
